# Generated by Django 5.1 on 2024-08-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
