# Generated by Django 5.1 on 2024-08-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_api", "0003_post_hashtags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="hashtags",
        ),
    ]
